GET http://localhost:4000/api/state/washington HTTP/1.1

### 

GET http://localhost:4000/api/states/ HTTP/1.1

###

GET http://localhost:4000/api/state/california/county/alameda HTTP/1.1

###

GET http://localhost:4000/api/counties HTTP/1.1